### ISSUE TITLE
Vulnerability: react-scripts > webpack-dev-server > yargs > yargs-parser

### ISSUE THREAD

**Issue by zw627** [zw627/case-study-search-room#41]
```
react-scripts > webpack-dev-server > yargs > yargs-parser
```

See https://github.com/webpack/webpack-dev-server/issues/2559 for more info.

**Comment by zw627** [comment]
Fixed in `webpack-dev-server` [3.11.0](https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.0).

Waiting for `react-scripts` to upgrade its `webpack-dev-server` dependency.

**Comment by dillu24** [comment]
Any idea how much time this will take until fixed?

**Comment by zw627** [comment]
> Any idea how much time this will take until fixed?

Unfortunately, no Create React App maintainers have yet to respond. *I mainly use my own Webpack boilerplate, and moments like this really shows its benefits.*
